package by.restaurant.controller.command;

public enum CommandName {

	SIGN_IN,
	SIGN_OUT,
	SIGN_UP,
	SHOW_MENU,
	CHANGE_LANGUAGE,
	ADD_DISH_TO_BASKET,
	NO_SUCH_COMMAND, 
	DELETE_DISH_FROM_BASKET, 
	CLEAR_BASKET,
	SHOW_BASKET,
	CREATE_ORDER,
	ALL_USER_ORDERS,
	PROFILE,
	SAVE_USER_CHANGES,
	CANCEL_ORDER,
	ALL_REVIEWS,
	CHANGE_PASSWORD,
	ALL_USERS,
	BAN_USER, 
	UNBAN_USER,
	ADMIN_MENU, 
	DELETE_DISH, 
	RESET_PASSWORD,
	CHANGE_DISH,
	ADD_DISH, 
	ADD_REVIEW, 
	DELETE_REVIEW,
	ALL_ORDERS, 
	DO_ORDER,
	CLOSE_ORDER,
	SEARCH_DISHES_BY_PART_OF_NAME, STAX_PARSER, EXPORT_TO_XML,


}
